// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ILB_NamedVariables","status":true,"description":"Exposes global objects $nv $ns $nc for named variables, switches and common events respectively","parameters":{}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"EventFloatingText","status":true,"description":"Displays floating text above events on the map.","parameters":{}},
{"name":"ILB_QuickTest","status":false,"description":"Auto starts the game","parameters":{}},
{"name":"SAN_MapGenerator","status":true,"description":"自動マップ生成 1.1.9\n自動的にマップを生成しイベントを配置します。","parameters":{"WallHight":"2","MinRoomSize":"4","MaxRoomSize":"10","MinRooms":"5","MaxRooms":"7","ShowOuterWall":"OFF"}},
{"name":"VE_DiagonalMovement","status":true,"description":"v1.00 - Allows diagonal movement for player and events.","parameters":{"Diagonal Adjust":"true","Diagonal Events":"true","Diagonal Fix":"false","Diagonal Trigger":"true","Corner Passability":"false\r"}},
{"name":"ILB_CustomFunctions","status":true,"description":"Exposes a global object $f to store custom functions for use in script calls.","parameters":{}},
{"name":"SimpleDungeonMinimap","status":true,"description":"Dungeon Minimap (SAN_MapGenerator) – PMD Style\nClean ES6 version + enemies + items","parameters":{"Tile size":"12","Event show distance":"3","X offset":"Math.floor(Graphics.width / 4)","Y offset":"Math.floor(Graphics.height / 4)"}},
{"name":"JKL_PersistentData","status":true,"description":"Jackkel's Persistent Data Plugin (v5)","parameters":{"Persistent Switches":"","Save Switches when Set":"","Persistent Variables":"10","Save Variables when Set":""}},
{"name":"ILB_CustomMainMenuOption","status":true,"description":"Adds custom options to the main menu which run common events.","parameters":{"Options List":"[9,\"Floor\",0,4]"}},
{"name":"YEP_MessageCore","status":true,"description":"v1.19 Adds more features to the Message Window to customized\nthe way your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward Key":"pagedown","Enable Fast Forward":"true","Word Wrapping":"false","Description Wrap":"false","Word Wrap Space":"false","Tight Wrap":"false","---Font---":"","Font Name":"GameFont","Font Name CH":"SimHei, Heiti TC, sans-serif","Font Name KR":"Dotum, AppleGothic, sans-serif","Font Size":"28","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","Font Outline":"4","Maintain Font":"false","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]","Name Box Auto Close":"false"}},
{"name":"ILB_ES6Modules","status":true,"description":"Allows you to load and use es6 modules.","parameters":{"Main module path":"js/plugins/modules/main.js"}},
{"name":"PMD_HUD","status":true,"description":"Pokemon Mystery Dungeon-style HUD (Top of screen) for Map Scene","parameters":{"Floor Variable ID":"22"}}
];
