//=============================================================================
// ILB_CustomFunctions.js
//=============================================================================

/*:
 * @plugindesc Exposes a global object $f to store custom functions for use in script calls.
 *
 * @author I_LIKE_BREAD7
 *
 * @help
 * This plugin creates a global object $f. You can add any functions you want to $f and 
 * then call them using script calls. This is useful for organizing custom game functions.
 * You can also include multiple copies of this plugin with different filenames for better
 * code separation.
 * 
 * Example usage:
 * Add a function to the plugin in the designated space like this
 *   $f.myFunction = function(param1, param2) {
 *       // Your code here
 *       console.log("Function called with params:", param1, param2);
 *   };
 *
 * Then in a script call, use like this:
 *   $f.myFunction("hello", 42);
 */

var $f = $f || {};

(function () {

    const distanceToFollow = 3;
    let currentEnemyIndex = 0;
    function moveEnemies() {
        const events = $gameMap.events();
        const realMoveSpeed = $gamePlayer.realMoveSpeed();
        for (; currentEnemyIndex < events.length; currentEnemyIndex++) {
            const event = events[currentEnemyIndex];
            if (!event || event._erased || event.isMoving() || !event.event().meta || !event.event().meta.enemy) {
                continue;
            }

            if (event.isStunned) {
                event.isStunned = false;
                continue;
            }

            event.setMoveSpeed(realMoveSpeed);
            const playerDistance = distance($gamePlayer, event);
            if (playerDistance === 1) {
                event.isAttacking = true;
                event.start();
                currentEnemyIndex++;
                return;
            } else if (playerDistance <= distanceToFollow || event.isSameRoomWithPlayer()) {
                event.moveTowardPlayer();
            } else {
                event.moveRandom();
            }
        }

        if (currentEnemyIndex >= events.length) {
            currentEnemyIndex = 0;
        }
    }

    const _Game_Event_unlock = Game_Event.prototype.unlock;
    Game_Event.prototype.unlock = function () {
        _Game_Event_unlock.call(this);

        console.log(this.event().meta)

        if (!this.event().meta || !this.event().meta.enemy) {
            return;
        }

        this.isAttacking = false;
        if ($gameSwitches.value(1)) { // Attack cancelled
            $gameSwitches.setValue(1, false);
        } else {
            moveEnemies();
        }
    }

    const _Game_Party_increaseSteps = Game_Party.prototype.increaseSteps;
    Game_Party.prototype.increaseSteps = function () {
        _Game_Party_increaseSteps.call(this);
        moveEnemies();
    };

    function distance(entity1, entity2) {
        return Math.max(
            Math.abs(entity1.x - entity2.x),
            Math.abs(entity1.y - entity2.y)
        );
    }

    $f.setEnemyTexts = () => {
        $gameMap.events().forEach($f.setEnemyText);
    }

    $f.setEnemyText = event => {
        if (!event || event._erased || !event.event().meta || !event.event().meta.enemy) {
            return;
        }

        const randomQuestion = pickRandom(quizData);
        const answers = [randomQuestion.answer];
        for (let i = 0; i < 3; i++) {
            let randomAnswer;
            let answer;
            do {
                randomAnswer = pickRandom(quizData);
                answer = randomAnswer.answer;
            } while (answers.includes(answer));
            answers.push(answer);
        }

        shuffle(answers);
        const correctIndex = answers.findIndex(answer => answer === randomQuestion.answer);
        const incorrectIndexes = [];
        for (let i = 0; i < 2; i++) {
            const incorrectAnswersIndexes = answers
                .map((_, index) => index)
                .filter(index => index !== correctIndex && !incorrectIndexes.includes(index));
            const randomIndexIndex = Math.floor(Math.random() * incorrectAnswersIndexes.length);
            incorrectIndexes.push(incorrectAnswersIndexes[randomIndexIndex]);
        }

        event.quiz = {
            question: randomQuestion.question,
            answers: answers,
            correct: correctIndex,
            incorrect: incorrectIndexes
        };
        console.log(event.quiz)

        $eventText.set(event.eventId(), event.quiz.question);
    }

    $f.placePortal = (x, y) => {
        const portalData = $dataMap.events.find(event => event && event.meta && event.meta.portal);
        if (!portalData) {
            console.warn('No portal event!');
            return;
        }

        const event = new Game_Event($gameMap.mapId(), portalData.id);
        $gameMap._events.push(event);
        event._eventId = $gameMap._events.indexOf(event);
        event.setPosition(x, y);
        addEventSprite(event);
    };

    function addEventSprite(event) {
        const sprite = new Sprite_Character(event);
        const spriteset = SceneManager._scene._spriteset;
        spriteset._characterSprites.push(sprite);
        spriteset._tilemap.addChild(sprite);
    }

    $f.enemyHit = enemyEvent => {
        if (enemyEvent.hit) {
            $eventText.clear(enemyEvent.eventId());
            if (enemyEvent.event().meta.portalEnemy) {
                $f.placePortal(enemyEvent.x, enemyEvent.y);
            }
            $gameMap.eraseEvent(enemyEvent.eventId());

        } else {
            enemyEvent.isStunned = true;
            enemyEvent.hit = true;
            $f.setEnemyText(enemyEvent);
        }
    }

    function pickRandom(array) {
        const randomIndex = Math.floor(Math.random() * array.length);
        return array[randomIndex];
    }

    /**
     * 
     * @param {[]} array 
     * @returns {[]} The same array shuffled in place
     */
    function shuffle(array) {
        for (let i = array.length - 1; i > 0; i--) {
            const randomIndex = Math.floor(Math.random() * (i + 1));

            const tmp = array[i];
            array[i] = array[randomIndex];
            array[randomIndex] = tmp;
        }

        return array;
    }

    const _Game_CharacterBase_checkEventTriggerTouchFront = Game_CharacterBase.prototype.checkEventTriggerTouchFront;
    Game_CharacterBase.prototype.checkEventTriggerTouchFront = function (d) {
        console.log(d);
        console.log('!!!!')
        // if (d % 2 !== 0) {
        //     var horz = ((d === 1 || d === 7) ? 4 : 6);
        //     var vert = ((d === 1 || d === 3) ? 2 : 8);
        //     var x2 = $gameMap.roundXWithDirection(this.x, horz);
        //     var y2 = $gameMap.roundYWithDirection(this.y, vert);
        //     this.checkEventTriggerTouch(x2, y2);
        //     if (!$gameMap.isEventRunning()) this.checkEventTriggerTouch(this.x, y2);
        //     if (!$gameMap.isEventRunning()) this.checkEventTriggerTouch(x2, this.y);
        // } else {
            _Game_CharacterBase_checkEventTriggerTouchFront.call(this, d)
        // }
    };

    const _Game_CharacterBase_moveDiagonally = Game_CharacterBase.prototype.moveDiagonally;
	Game_CharacterBase.prototype.moveDiagonally = function(horz, vert) {
        _Game_CharacterBase_moveDiagonally.call(this, horz, vert);
		if (!this.isMovementSucceeded()) {
            this.checkEventTriggerTouchFront(this._diagDir);
        };
	};

    const quizData = [
        { question: 'aku', answer: '私' },
        { question: 'kau', answer: 'あなた' },
        { question: 'tidak', answer: 'いいえ' },
        { question: 'ini', answer: 'これ' },
        { question: 'itu', answer: 'それ' },
        { question: 'dan', answer: 'そして' },
        { question: 'dia', answer: '彼' },
        { question: 'di', answer: 'で' },
        { question: 'akan', answer: '意思' },
        { question: 'apa', answer: '何' },
        { question: 'kita', answer: '私たちは' },
        { question: 'untuk', answer: 'のために' },
        { question: 'bisa', answer: 'できる' },
        { question: 'ada', answer: 'がある' },
        { question: 'tak', answer: 'ない' },
        { question: 'mereka', answer: '彼らは' },
        { question: 'anda', answer: 'あなた' },
        { question: 'saya', answer: '私' },
        { question: 'dari', answer: 'から' },
        { question: 'ya', answer: 'はい' },
        { question: 'tapi', answer: 'しかし' },
        { question: 'kami', answer: '私たちは' },
        { question: 'ke', answer: 'に' },
        { question: 'sudah', answer: 'すでに' },
        { question: 'kamu', answer: 'あなた' },
        { question: 'adalah', answer: 'は' },
        { question: 'orang', answer: '人' },
        { question: 'saja', answer: 'ただ' },
        { question: 'ingin', answer: 'したい' },
        { question: 'jika', answer: 'もし' },
        { question: 'hanya', answer: 'のみ' },
        { question: 'semua', answer: '全て' },
        { question: 'sekarang', answer: '今' },
        { question: 'jadi', answer: 'それで' },
        { question: 'dalam', answer: 'で' },
        { question: 'bagaimana', answer: 'どうやって' },
        { question: 'jangan', answer: 'しないでください' },
        { question: 'lagi', answer: 'また' },
        { question: 'punya', answer: '持っている' },
        { question: 'oh', answer: 'おお' },
        { question: 'pada', answer: 'の上' },
        { question: 'kalian', answer: 'あなた' },
        { question: 'karena', answer: 'なぜなら' },
        { question: 'sangat', answer: 'とても' },
        { question: 'satu', answer: '1つ' },
        { question: 'mau', answer: 'したい' },
        { question: 'siapa', answer: '誰が' },
        { question: 'telah', answer: 'もっている' },
        { question: 'hal', answer: '案件' },
        { question: 'saat', answer: '一瞬' },
        { question: 'kenapa', answer: 'なぜ' },
        { question: 'atau', answer: 'または' },
        { question: 'datang', answer: '来る' },
        { question: 'begitu', answer: 'それで' },
        { question: 'sesuatu', answer: '何か' },
        { question: 'banyak', answer: 'たくさん' },
        { question: 'benar', answer: '正しい' },
        { question: 'menjadi', answer: 'なる' },
        { question: 'melihat', answer: '見る' },
        { question: 'melakukan', answer: 'する' },
        { question: 'terima', answer: '受け入れる' },
        { question: 'lihat', answer: '見て' },
        { question: 'seorang', answer: '1つの' },
        { question: 'bahwa', answer: 'それ' },
        { question: 'kalau', answer: 'もし' },
        { question: 'hei', answer: 'おい' },
        { question: 'bagus', answer: '良い' },
        { question: 'bilang', answer: '言った' },
        { question: 'oke', answer: 'わかった' },
        { question: 'baiklah', answer: 'わかった' },
        { question: 'mana', answer: 'どこ' },
        { question: 'keluar', answer: '外出' },
        { question: 'lalu', answer: 'それから' },
        { question: 'malam', answer: '夕方' },
        { question: 'membuat', answer: '作る' },
        { question: 'mati', answer: '死んだ' },
        { question: 'sedang', answer: '現在' },
        { question: 'memiliki', answer: '自分の' },
        { question: 'tahun', answer: '年' },
        { question: 'sekali', answer: 'とても' },
        { question: 'anak', answer: '子供' },
        { question: 'baru', answer: '新しい' },
        { question: 'dapat', answer: 'できる' },
        { question: 'beberapa', answer: '多数の' },
        { question: 'ayah', answer: '父親' },
        { question: 'sendiri', answer: '一人で' },
        { question: 'katakan', answer: '言う' },
        { question: 'mengapa', answer: 'なぜ' },
        { question: 'sebuah', answer: 'あ' },
        { question: 'kan', answer: '右' },
        { question: 'sama', answer: '同じ' },
        { question: 'tunggu', answer: '待って' },
        { question: 'salah', answer: '間違っている' },
        { question: 'semuanya', answer: 'すべて' },
        { question: 'rumah', answer: '家' },
        { question: 'ia', answer: '彼' },
        { question: 'masuk', answer: '入力' },
        { question: 'cepat', answer: '速い' },
        { question: 'dengar', answer: '聞く' },
        { question: 'besar', answer: '大きい' },
        { question: 'disini', answer: 'ここ' },
        { question: 'pasti', answer: 'ある' },
        { question: 'yg', answer: 'どれの' },
        { question: 'ibu', answer: '母親' },
        { question: 'masalah', answer: '問題' },
        { question: 'benar-benar', answer: '本当に' },
        { question: 'belum', answer: 'まだ' },
        { question: 'pak', answer: 'パック' },
        { question: 'bicara', answer: '話す' },
        { question: 'dua', answer: '二' },
        { question: 'yeah', answer: 'うん' },
        { question: 'seseorang', answer: '誰か' },
        { question: 'melakukannya', answer: 'それをやる' },
        { question: 'setelah', answer: '後' },
        { question: 'baik-baik', answer: '大丈夫' },
        { question: 'bahkan', answer: '平' },
        { question: 'berada', answer: 'は' },
        { question: 'menemukan', answer: '探す' },
        { question: 'sedikit', answer: '少し' },
        { question: 'bertemu', answer: '会う' },
        { question: 'mendapatkan', answer: '得る' },
        { question: 'percaya', answer: '信じる' },
        { question: 'oleh', answer: 'による' },
        { question: 'makan', answer: '食べる' },
        { question: 'lama', answer: '長さ' },
        { question: 'atas', answer: 'の上' },
        { question: 'ku', answer: '私の' },
        { question: 'tinggal', answer: '滞在する' },
        { question: 'bekerja', answer: '仕事' },
        { question: 'wanita', answer: '女性' },
        { question: 'padamu', answer: 'あなたへ' },
        { question: 'sayang', answer: 'ダーリン' },
        { question: 'kali', answer: '時間' },
        { question: 'tetap', answer: 'まだ' },
        { question: 'hey', answer: 'おい' },
        { question: 'cara', answer: '方法' },
        { question: 'berhenti', answer: '停止' },
        { question: 'jalan', answer: '道' },
        { question: 'setiap', answer: '毎' },
        { question: 'berpikir', answer: '考える' },
        { question: 'mulai', answer: '始める' },
        { question: 'mari', answer: 'させて' },
        { question: 'membunuh', answer: '殺す' },
        { question: 'luar', answer: '外' },
        { question: 'kecil', answer: '小さい' },
        { question: 'sebelum', answer: '前に' },
        { question: 'diri', answer: '自己' },
        { question: 'bersama', answer: '一緒に' },
        { question: 'mengambil', answer: '取る' },
        { question: 'boleh', answer: '5月' },
        { question: 'the', answer: 'その' },
        { question: 'mencari', answer: '探す' },
        { question: 'uang', answer: 'お金' },
        { question: 'apapun', answer: '何でも' },
        { question: 'senang', answer: 'のように' },
        { question: 'kurasa', answer: '私は思う' },
        { question: 'sebenarnya', answer: '実は' },
        { question: 'mencoba', answer: '試す' },
        { question: 'gadis', answer: '女の子' },
        { question: 'tanpa', answer: 'それなし' },
        { question: 'jam', answer: '時' },
        { question: 'para', answer: 'のために' },
        { question: 'membawa', answer: '持ってくる' },
        { question: 'yah', answer: 'はい' },
        { question: 'orang-orang', answer: '人々' },
        { question: 'itulah', answer: 'それでおしまい' },
        { question: 'ingat', answer: '覚えて' },
        { question: 'kemudian', answer: 'それから' },
        { question: 'siap', answer: '準備ができて' },
        { question: 'biarkan', answer: 'させて' },
        { question: 'maksudku', answer: 'つまり' },
        { question: 'terus', answer: '続けて' },
        { question: 'gila', answer: 'クレイジー' },
        { question: 'pun', answer: '平' },
        { question: 'tuan', answer: 'お客様' },
        { question: 'sakit', answer: '病気' },
        { question: 'tidur', answer: '寝る' },
        { question: 'pulang', answer: '家に帰れ' },
        { question: 'seharusnya', answer: 'すべき' },
        { question: 'kepada', answer: 'に' },
        { question: 'memang', answer: 'もちろん' },
        { question: 'takut', answer: '恐れている' },
        { question: 'terlihat', answer: '見た' },
        { question: 'nama', answer: '名前' },
        { question: 'i', answer: '私' },
        { question: 'sial', answer: '不運' },
        { question: 'minta', answer: '求める' },
        { question: 'mobil', answer: '車' },
        { question: 'membantu', answer: 'ヘルプ' },
        { question: 'terakhir', answer: 'ファイナル' },
        { question: 'biasa', answer: '普通' },
        { question: 'cinta', answer: '愛' },
        { question: 'mu', answer: 'あなたの' },
        { question: 'sebentar', answer: 'ちょっと' },
        { question: 'padanya', answer: '彼に' },
        { question: 'bagian', answer: '一部' },
        { question: 'bodoh', answer: 'バカ' },
        { question: 'sialan', answer: 'くそ' },
        { question: 'manusia', answer: '男' },
        { question: 'tiga', answer: '三つ' },
        { question: 'berhasil', answer: '成功する' },
        { question: 'sungguh', answer: '本当に' },
        { question: 'mendengar', answer: '聞く' },
        { question: 'tepat', answer: '適切な' },
        { question: 'bawah', answer: 'より低い' },
        { question: 'berikan', answer: '与える' },
        { question: 'ambil', answer: '取る' },
        { question: 'pagi', answer: '朝' },
        { question: 'air', answer: '水' },
        { question: 'keluarga', answer: '家族' },
        { question: 'hai', answer: 'お' },
        { question: 'kehilangan', answer: '失った' },
        { question: 'maafkan', answer: '私を許して' },
        { question: 'untukmu', answer: 'あなたのために' },
        { question: 'bagi', answer: 'のために' },
        { question: 'tangan', answer: '手' },
        { question: 's', answer: 's' },
        { question: 'menunggu', answer: '待って' },
        { question: 'ikut', answer: 'フォローする' },
        { question: 'melihatnya', answer: '見る' },
        { question: 'masa', answer: '時間' },
        { question: 'pekerjaan', answer: '仕事' },
        { question: 'ah', answer: 'ああ' },
        { question: 'paling', answer: 'ほとんど' },
        { question: 'peduli', answer: 'ケア' },
        { question: 'aneh', answer: '奇妙な' },
        { question: 'penting', answer: '重要' },
        { question: 'tadi', answer: '以前' },
        { question: 'si', answer: 'シ' },
        { question: 'selesai', answer: '終了した' },
        { question: 'suatu', answer: '何か' },
        { question: 'terbaik', answer: '最高' },
        { question: 'khawatir', answer: '心配' },
        { question: 'tenang', answer: '落ち着いた' },
        { question: 'hentikan', answer: '停止' },
        { question: 'disana', answer: 'そこには' },
        { question: 'bisakah', answer: 'できる' },
        { question: 'coba', answer: '試す' },
        { question: 'uh', answer: 'えーと' },
        { question: 'duduk', answer: '座って下さい' },
        { question: 'sebelumnya', answer: '以前' },
        { question: 'secara', answer: 'ある意味で' },
        { question: 'maka', answer: 'それで' },
        { question: 'minum', answer: '飲む' },
        { question: 'tn', answer: '氏' },
        { question: 'a', answer: '1つの' },
        { question: 'sejak', answer: '以来' },
        { question: 'hampir', answer: 'ほとんど' },
        { question: 'kemari', answer: 'ここ' },
        { question: 'tetapi', answer: 'しかし' },
        { question: 'soal', answer: '質問' },
        { question: 'maksudmu', answer: 'もしかして' },
        { question: 'menggunakan', answer: '使用' },
        { question: 'tau', answer: '知る' },
        { question: 'diam', answer: '静けさ' },
        { question: 'aman', answer: '安全' },
        { question: 'berjalan', answer: '歩く' },
        { question: 'buat', answer: 'のために' },
        { question: 'sulit', answer: '難しい' },
        { question: 'senjata', answer: '武器' },
        { question: 'iya', answer: 'はい' },
        { question: 'inginkan', answer: '欲しい' },
        { question: 'kapan', answer: 'いつ' },
        { question: 'sekitar', answer: 'その周り' },
        { question: 'pintu', answer: 'ドア' },
        { question: 'nak', answer: '息子' },
        { question: 'hati', answer: '心臓' },
        { question: 'nah', answer: '今' },
        { question: 'bermain', answer: '遊ぶ' },
        { question: 'cari', answer: '検索' },
        { question: 'dekat', answer: '近く' },
        { question: 'nya', answer: '彼の' },
        { question: 'dengannya', answer: '彼と一緒に' },
        { question: 'akhirnya', answer: 'ついに' },
        { question: 'kumohon', answer: 'お願いします' },
        { question: 'denganku', answer: '私と一緒に' },
        { question: 'agar', answer: 'となることによって' },
        { question: 'benarkah', answer: 'それは本当ですか' },
        { question: 'berakhir', answer: '終わり' },
        { question: 'ayahmu', answer: 'あなたのお父さん' },
        { question: 'memberitahu', answer: 'あなたに伝えている' },
        { question: 'menarik', answer: '面白い' },
        { question: 'cantik', answer: '美しい' },
        { question: 'berubah', answer: '変更された' },
        { question: 'kupikir', answer: '私は思う' },
        { question: 'keras', answer: '難しい' },
        { question: 'mata', answer: '目' },
        { question: 'dokter', answer: '医者' },
        { question: 'lainnya', answer: '他の' },
        { question: 'beritahu', answer: '教えて' },
        { question: 'kemana', answer: 'どこへ' },
        { question: 'serius', answer: '深刻な' },
        { question: 'kuat', answer: '強い' },
        { question: 'meminta', answer: 'リクエスト' },
        { question: 'membuatku', answer: '私を作る' },
        { question: 'bunuh', answer: '殺す' },
        { question: 'pergilah', answer: '行く' },
        { question: 'kehidupan', answer: '人生' },
        { question: 'berharap', answer: '希望' },
        { question: 'bangun', answer: '起きる' },
        { question: 'menurutmu', answer: 'あなたによると' },
        { question: 'beri', answer: '与える' },
        { question: 'kata', answer: '言う' },
        { question: 'darah', answer: '血' },
        { question: 'dengarkan', answer: '聞く' },
        { question: 'kamar', answer: '部屋' },
        { question: 'kulakukan', answer: '私はします' },
        { question: 'berkata', answer: '言った' },
        { question: 'menyenangkan', answer: '楽しい' },
        { question: 'dilakukan', answer: '終わり' },
        { question: 'kosong', answer: '空の' },
        { question: 'b1', answer: 'b1' },
        { question: 'eh', answer: 'えー' },
        { question: 'belakang', answer: '後ろに' },
        { question: 'raja', answer: '王' },
        { question: 'dasar', answer: 'ベース' },
        { question: 'bajingan', answer: 'ろくでなし' },
        { question: 'biar', answer: 'させて' },
        { question: 'makanan', answer: '食べ物' },
        { question: 'bantuan', answer: 'ヘルプ' },
        { question: 'dapatkan', answer: '得る' },
        { question: 'ruang', answer: '部屋' },
        { question: 'demi', answer: 'のために' },
        { question: 'marah', answer: '怒り' },
        { question: 'membiarkan', answer: 'させて' },
        { question: 'lepaskan', answer: '手放す' },
        { question: 'daripada', answer: 'よりも' },
        { question: 'it', answer: 'それ' },
        { question: '4ch000000', answer: '4ch000000' },
        { question: 'berusaha', answer: '試す' },
        { question: 'diriku', answer: '自分自身' },
        { question: 'fncandara', answer: 'フカンダラ' },
        { question: 'telepon', answer: '電話' },
        { question: 'perang', answer: '戦争' },
        { question: 'pertanyaan', answer: '質問' },
        { question: 'belajar', answer: '勉強' },
        { question: 'suara', answer: '声' },
        { question: 'amerika', answer: 'アメリカ人' },
        { question: 'lupa', answer: '忘れる' },
        { question: 'lihatlah', answer: '見てください' },
        { question: 'muda', answer: '若い' },
        { question: 'pikirkan', answer: '考えてみてください' },
        { question: 'ibumu', answer: 'あなたのお母さん' },
        { question: 'menuju', answer: '行く' },
        { question: 'permisi', answer: 'すみません' },
        { question: 'langsung', answer: '直接' },
        { question: 'wow', answer: 'おお' },
        { question: 'paham', answer: '理解する' },
        { question: 'antara', answer: '間' },
        { question: 'membutuhkan', answer: '必要' },
        { question: 'tinggi', answer: '高い' },
        { question: 'turun', answer: '下' },
        { question: 'ide', answer: 'アイデア' },
        { question: 'kaki', answer: '足' },
        { question: 'penuh', answer: '満杯' },
        { question: 'sendirian', answer: '一人で' },
        { question: 'lima', answer: '五' },
        { question: 'ibuku', answer: '私の母' },
        { question: 'kematian', answer: '死' },
        { question: 'berdiri', answer: '立つ' },
        { question: 'to', answer: 'に' },
        { question: 'kecuali', answer: 'を除外する' },
        { question: 'menang', answer: '勝つ' },
        { question: 'and', answer: 'そして' },
        { question: 'menerima', answer: '受け入れる' },
        { question: 'silakan', answer: 'お願いします' },
        { question: 'tanah', answer: '土地' },
        { question: 'bicarakan', answer: '話す' },
        { question: 'lucu', answer: '面白い' },
        { question: 'buka', answer: '開ける' },
        { question: 'melawan', answer: '反対する' },
        { question: 'um', answer: 'えーと' },
        { question: 'agen', answer: 'エージェント' },
        { question: 'melalui', answer: 'を通して' },
        { question: 'rasanya', answer: 'こんな感じ' },
        { question: 'sepanjang', answer: '全体を通して' },
        { question: 'akhir', answer: '終わり' },
        { question: 'bu', answer: '奥様' },
        { question: 'artinya', answer: 'それはつまり' },
        { question: 'terlambat', answer: '遅い' },
        { question: 'mulia', answer: '素晴らしい' },
        { question: 'untukku', answer: '私にとって' },
        { question: 'temukan', answer: '探す' },
        { question: 'well', answer: '良い' },
        { question: 'kesalahan', answer: 'エラー' },
        { question: 'silahkan', answer: 'お願いします' },
        { question: 'mencintaimu', answer: '愛している' },
        { question: 'nomor', answer: '番号' },
        { question: 'api', answer: '火' },
        { question: 'guru', answer: '教師' },
        { question: 'bahagia', answer: 'ハッピー' },
        { question: 'waktunya', answer: '時間' },
        { question: 'film', answer: '膜' },
        { question: 'tiba', answer: '到着' },
        { question: 'bantu', answer: 'ヘルプ' },
        { question: 'panas', answer: '熱い' },
        { question: 'memakai', answer: '使用' },
        { question: 'okay', answer: 'わかった' },
        { question: 'kubilang', answer: '私は言った' },
        { question: 'segalanya', answer: 'すべて' },
        { question: 'setidaknya', answer: '少なくとも' },
        { question: 'keren', answer: 'いいね' },
        { question: 'membunuhnya', answer: '彼を殺す' },
        { question: 'no', answer: 'いいえ' },
        { question: 'jawab', answer: '答え' },
        { question: 'pesan', answer: 'メッセージ' },
        { question: 'bertahan', answer: '耐える' },
        { question: 'bayi', answer: '赤ちゃん' },
        { question: 'bahasa', answer: '言語' },
        { question: 'kantor', answer: 'オフィス' },
        { question: 'putri', answer: '娘' },
        { question: 'empat', answer: '4つ' },
        { question: 'tinggalkan', answer: '離れる' },
        { question: 'muncul', answer: '現れる' },
        { question: 'omong', answer: '話す' },
        { question: 'awal', answer: '始まり' },
        { question: 'anakku', answer: '私の子供' },
        { question: 'penjara', answer: '刑務所' },
        { question: 'nyata', answer: '本物' },
        { question: 'sempurna', answer: '完璧' },
        { question: 'semoga', answer: 'うまくいけば' },
        { question: 'janji', answer: '約束' },
        { question: 'bercanda', answer: '冗談' },
        { question: 'tampak', answer: '見た目' },
        { question: 'siapapun', answer: '誰でも' },
        { question: 'menghancurkan', answer: '破壊する' },
        { question: 'kesini', answer: 'ここに来て' },
        { question: 'kelas', answer: 'クラス' },
        { question: 'laki-laki', answer: '男' },
        { question: 'whoa', answer: 'うわあ' },
        { question: 'ulang', answer: '繰り返す' },
        { question: 'jumpa', answer: 'またね' },
        { question: 'sebaiknya', answer: 'すべき' },
        { question: 'menembak', answer: 'シュート' },
        { question: 'namun', answer: 'しかし' },
        { question: 'permainan', answer: 'ゲーム' },
        { question: 'hal-hal', answer: 'もの' },
        { question: 'sam', answer: 'サム' },
        { question: 'tahan', answer: '立つ' },
        { question: 'sering', answer: '頻繁' },
        { question: 'tutup', answer: '閉鎖' },
        { question: 'sang', answer: 'その' },
        { question: 'jack', answer: 'ジャック' },
        { question: 'pembunuhan', answer: '殺人' },
        { question: 'perintah', answer: '注文' },
        { question: 'jahat', answer: '邪悪な' },
        { question: 'hubungan', answer: '繋がり' },
        { question: 'terbang', answer: '飛ぶ' },
        { question: 'dingin', answer: '寒い' },
        { question: 'mendapatkannya', answer: 'それを得る' },
        { question: 'berikutnya', answer: '次' },
        { question: 'pasukan', answer: '軍' },
        { question: 'hati-hati', answer: '気をつけて' },
        { question: 'laut', answer: '海' },
        { question: 'by', answer: 'による' },
        { question: 'me', answer: '自分' },
        { question: 'meskipun', answer: 'それでも' },
        { question: 'membawanya', answer: '持ってきて' },
        { question: 'huh', answer: 'はぁ' },
        { question: 'perempuan', answer: '女性' },
        { question: 'segala', answer: '全て' },
        { question: 'menangkap', answer: 'キャッチ' },
        { question: 'harusnya', answer: 'すべきだ' },
        { question: 'tanda', answer: 'サイン' },
        { question: 'mundur', answer: '一歩下がる' },
        { question: 'mesin', answer: '機械' },
        { question: 'in', answer: 'で' },
        { question: 'barang', answer: '品' },
        { question: 'begini', answer: 'このような' },
        { question: 'mimpi', answer: '夢' },
        { question: 'bisnis', answer: '仕事' },
        { question: 'bukanlah', answer: 'ではない' },
        { question: 'menangis', answer: '泣く' },
        { question: 'menelepon', answer: '電話' },
        { question: 'berbahaya', answer: '危険な' },
        { question: 'kukatakan', answer: '私は言う' },
        { question: 'pikiran', answer: '考え' },
        { question: 'mencuri', answer: '窃盗' },
        { question: 'pakai', answer: '使用' },
        { question: 'berani', answer: '勇敢な' },
        { question: 'dr.', answer: 'ドクター' },
        { question: 'agak', answer: 'それよりも' },
        { question: 'melindungi', answer: '守る' },
        { question: 'benda', answer: '物体' },
        { question: 'membaca', answer: '読む' },
        { question: 'setengah', answer: '半分' },
        { question: 'dariku', answer: '私から' },
        { question: 'hitam', answer: '黒' },
        { question: 'ha', answer: 'ハ' },
        { question: 'enak', answer: 'ニース' },
        { question: 'lagu', answer: '歌' },
        { question: 'kemarin', answer: '昨日' },
        { question: 'tubuh', answer: '体' },
        { question: 'man', answer: '男' },
        { question: 'memikirkan', answer: '考える' },
        { question: 'inilah', answer: 'ここにあります' },
        { question: 'bersalah', answer: '有罪' },
        { question: 'mengirim', answer: '送信' },
        { question: 'mengenai', answer: 'について' },
        { question: 'namaku', answer: '私の名前' },
        { question: 'mengubah', answer: '変化' },
        { question: 'saling', answer: 'お互い' },
        { question: 'harap', answer: 'お願いします' },
        { question: 'paman', answer: '叔父' },
        { question: 'mendengarkan', answer: '聞く' },
        { question: 'selamanya', answer: '永遠に' },
        { question: 'terhadap', answer: 'に' },
        { question: 'saudara', answer: 'あなた' },
        { question: 'hukum', answer: '法' },
        { question: 'menghilang', answer: '消える' },
        { question: 'tugas', answer: 'タスク' },
        { question: 'betapa', answer: 'どうやって' },
        { question: 'hmm', answer: 'ふーむ' },
        { question: 'obat', answer: '薬' },
        { question: 'manis', answer: '甘い' },
        { question: 'sebelah', answer: '隣接' },
        { question: 'bagiku', answer: '私にとって' },
        { question: 'merasakan', answer: '感じる' },
        { question: 'fs60', answer: 'fs60' },
        { question: 'informasi', answer: '情報' },
        { question: 'selain', answer: 'その上' },
        { question: 'new', answer: '新しい' },
        { question: 'sisi', answer: '側' },
        { question: 'juta', answer: '百万' },
        { question: 'istri', answer: '妻' },
        { question: 'my', answer: '私の' },
        { question: 'keadaan', answer: '状態' },
        { question: 'pernikahan', answer: '結婚式' },
        { question: 'saatnya', answer: '時間だ' },
        { question: 'entahlah', answer: '知るか' },
        { question: 'kesana', answer: 'そこには' },
        { question: 'bersama-sama', answer: '一緒に' },
        { question: 'pindah', answer: '動く' },
        { question: 'sadar', answer: 'わかっている' },
        { question: 'm', answer: 'メートル' },
        { question: 'pribadi', answer: '個人的' },
        { question: 'temanku', answer: '私の友人' },
        { question: 'menyesal', answer: '後悔' },
        { question: 'korban', answer: '被害者' },
        { question: 'wajah', answer: '顔' },
        { question: 'enam', answer: '六' },
        { question: 'presiden', answer: '社長' },
        { question: 'inggris', answer: '英語' },
        { question: 'bergabung', answer: '参加する' },
        { question: 'udara', answer: '空気' },
        { question: 'melewati', answer: '合格' },
        { question: 'batu', answer: 'ロック' },
        { question: 'gunakan', answer: '使用' },
        { question: 'mengalami', answer: '経験' },
        { question: 'pintar', answer: '頭がいい' },
        { question: 'mr', answer: '氏' },
        { question: 'sibuk', answer: '忙しい' },
        { question: 'menghentikan', answer: '停止' },
        { question: 'memeriksa', answer: '検査する' },
        { question: 'berjanji', answer: '約束' },
        { question: 'bola', answer: 'ボール' },
        { question: 'keamanan', answer: '安全' },
        { question: 'mampu', answer: '有能' },
        { question: 'gagal', answer: '失敗' },
        { question: 'panjang', answer: '長さ' },
        { question: 'dolar', answer: 'ドル' },
        { question: 'bos', answer: 'ボス' },
        { question: 'musik', answer: '音楽' },
        { question: 'panggil', answer: '電話' },
        { question: 'kereta', answer: '電車' },
        { question: 'hi', answer: 'こんにちは' },
        { question: 'mohon', answer: 'お願いします' },
        { question: 'menyerang', answer: '攻撃' },
        { question: 'tanganmu', answer: 'あなたの手' },
        { question: 'pakaian', answer: '服' },
        { question: 'foto', answer: '写真' },
        { question: 'akal', answer: '理由' },
        { question: 'kartu', answer: 'カード' },
        { question: 'mencintai', answer: '愛' },
        { question: 'perasaan', answer: 'フィーリング' },
        { question: 'jenis', answer: 'タイプ' },
        { question: 'mandi', answer: '入浴' },
        { question: 'mempunyai', answer: '持っている' },
        { question: 'membantumu', answer: 'あなたを助ける' },
        { question: 'maksud', answer: '意味' },
        { question: 'kecelakaan', answer: '事故' },
        { question: 'teman-teman', answer: '友達' },
        { question: 'memanggil', answer: '電話' },
        { question: 'makhluk', answer: '生き物' },
        { question: 'kabur', answer: 'ぼやけた' },
        { question: 'apos', answer: 'アポス' },
        { question: 'memulai', answer: '始める' },
        { question: 'detik', answer: '2番' },
        { question: 'menurut', answer: 'によると' },
        { question: 'kini', answer: '今' },
        { question: 'hantu', answer: 'おばけ' },
        { question: 'jaga', answer: 'ガード' },
        { question: 'cocok', answer: '適切な' },
        { question: 'posisi', answer: '位置' },
        { question: 'namamu', answer: 'あなたの名前' },
        { question: 'selanjutnya', answer: 'さらに' },
        { question: 'mengatakannya', answer: '言ってください' },
        { question: 'keberatan', answer: '物体' },
        { question: 'tertarik', answer: '興味がある' },
        { question: 'catatan', answer: 'メモ' },
        { question: 'tujuan', answer: '客観的' },
        { question: 'kanan', answer: '右' },
        { question: 'kalah', answer: '失った' },
        { question: 'neraka', answer: '地獄' },
        { question: 'pukul', answer: '時' },
        { question: 'planet', answer: '惑星' },
        { question: 'menyelesaikan', answer: '仕上げる' },
        { question: 'khusus', answer: '特別' },
        { question: 'masalahnya', answer: '問題' },
        { question: 'periksa', answer: 'チェック' },
        { question: 'hutan', answer: '森' },
        { question: 'menonton', answer: '時計' },
        { question: 'utara', answer: '北' },
        { question: 'utama', answer: '主要' },
        { question: 'kamera', answer: 'カメラ' },
        { question: 'burung', answer: '鳥' },
        { question: 'dewa', answer: '神' },
        { question: 'cahaya', answer: 'ライト' },
        { question: 'entah', answer: '知るか' },
        { question: 'hah', answer: 'はぁ' },
        { question: 'pantas', answer: 'ちゃんとした' },
        { question: 'disebut', answer: 'と呼ばれる' },
        { question: 'pahlawan', answer: 'ヒーロー' },
        { question: 'terlibat', answer: '関与した' },
        { question: 'situasi', answer: '状況' },
        { question: 'gambar', answer: '写真' },
        { question: 'kejahatan', answer: '犯罪' },
        { question: 'lee', answer: 'リー' },
        { question: 'misi', answer: 'ミッション' },
        { question: 'percayalah', answer: '私を信じて' },
        { question: 'perhatian', answer: '注意' },
        { question: 'gue', answer: '私' },
        { question: 'on', answer: 'の上' },
        { question: 'don', answer: 'ドン' },
        { question: 'membunuhku', answer: '私を殺して' },
        { question: 'menurutku', answer: '私によると' },
        { question: 'sir', answer: 'お客様' },
        { question: 'kiri', answer: '左' },
        { question: 'kalinya', answer: '初めて' },
        { question: 'ketakutan', answer: '恐れている' },
        { question: 'menjual', answer: '売る' },
        { question: 'kotak', answer: '箱' },
        { question: 'terdengar', answer: '聞いた' },
        { question: 'kuda', answer: '馬' },
        { question: 'sejauh', answer: 'の限り' },
        { question: 'alam', answer: '自然' },
        { question: 'kemarilah', answer: 'ここに来て' },
        { question: 'mengganggu', answer: 'わざわざ' },
        { question: 'pistol', answer: '銃' },
        { question: 'hello', answer: 'こんにちは' },
        { question: 'sepertimu', answer: 'あなたのような' },
        { question: 'ikuti', answer: 'フォローする' },
        { question: 'bahaya', answer: '危険' },
        { question: 'nenek', answer: 'おばあちゃん' },
        { question: 'gelap', answer: '暗い' },
        { question: 'ahli', answer: '専門家' },
        { question: 'main', answer: '遊ぶ' },
        { question: 'kopi', answer: 'コーヒー' },
        { question: 'merupakan', answer: 'は' },
        { question: 'ratu', answer: '女王' },
        { question: 'kemungkinan', answer: '可能性' },
        { question: 'diterjemahkan', answer: '翻訳された' },
        { question: 'kejadian', answer: '事件' },
        { question: 'balik', answer: '戻ってくる' },
        { question: 'detektif', answer: '探偵' },
        { question: 'daftar', answer: 'リスト' },
        { question: 'sejarah', answer: '歴史' },
        { question: 'nyaman', answer: '快適' },
        { question: 'daging', answer: '肉' },
        { question: 'keputusan', answer: '決断' },
        { question: 'caranya', answer: '方法' },
        { question: 'ceritakan', answer: '教えて' },
        { question: 'bernama', answer: '名前' },
        { question: 'layak', answer: '価値がある' },
        { question: 'penjaga', answer: 'ガード' },
        { question: 'alat', answer: '道具' },
        { question: 'kulit', answer: '肌' },
        { question: 'sesuai', answer: 'に従って' },
        { question: 'persetan', answer: 'くそ' },
        { question: 'temanmu', answer: 'あなたの友達' },
        { question: 'york', answer: 'ヨーク' },
        { question: 'tiba-tiba', answer: '突然' },
        { question: 'penyihir', answer: '魔女' },
        { question: 'sampah', answer: 'ごみ' },
        { question: 'bersumpah', answer: '誓う' },
        { question: 'menghubungi', answer: '接触' },
        { question: 'darimu', answer: 'あなたから' },
        { question: 'memastikan', answer: '確保する' },
        { question: 'bohong', answer: '嘘' },
        { question: 'tanya', answer: '聞く' },
        { question: 'menjelaskan', answer: '説明する' },
        { question: 'david', answer: 'デビッド' },
        { question: 'malu', answer: '恥ずかしい' },
        { question: 'kaya', answer: 'リッチ' },
        { question: 'dah', answer: '終わり' },
        { question: 'monster', answer: 'モンスター' },
        { question: 'mayat', answer: '死体' },
        { question: 'frank', answer: 'フランク' },
        { question: 'minuman', answer: '飲む' },
        { question: 'tangkap', answer: 'キャッチ' },
        { question: 'meja', answer: 'テーブル' },
        { question: 'pacar', answer: '彼氏' },
        { question: 'digunakan', answer: '使用済み' },
        { question: 'daerah', answer: 'エリア' },
        { question: 'ikan', answer: '魚' },
        { question: 'angkat', answer: 'リフト' },
        { question: 'pengacara', answer: '弁護士' },
        { question: 'michael', answer: 'マイケル' },
        { question: 'bau', answer: '匂い' },
        { question: 'normal', answer: '普通' },
        { question: 'harapan', answer: '希望' },
        { question: 'ampun', answer: '私を許して' },
        { question: 'butuhkan', answer: '必要' },
        { question: 'bank', answer: '銀行' },
        { question: 'prajurit', answer: '兵士' },
        { question: 'kabarmu', answer: 'あなたのニュース' },
        { question: 'menempatkan', answer: '置く' },
        { question: 'selatan', answer: '南' },
        { question: 'lelah', answer: '疲れた' },
        { question: 'dapatkah', answer: 'できる' },
        { question: 'pohon', answer: '木' },
        { question: 'sebagian', answer: '一部' },
        { question: 'menemui', answer: '会う' },
        { question: 'apa-apaan', answer: 'なんてこった' },
        { question: 'pusat', answer: '中心' },
        { question: 'maju', answer: '進む' },
        { question: 'menjawab', answer: '答え' },
        { question: 'pastikan', answer: '確認する' },
        { question: 'ibunya', answer: '彼の母親' },
        { question: 'will', answer: '意思' },
        { question: 'o', answer: 'o' },
        { question: 'urusan', answer: '事務' },
        { question: 'diluar', answer: '外' },
        { question: 'latihan', answer: 'エクササイズ' },
        { question: 'katanya', answer: '彼は言った' },
        { question: 'tersisa', answer: '残り' },
        { question: 'tewas', answer: '死んだ' },
        { question: 'tembakan', answer: 'ショット' },
        { question: 'keparat', answer: 'ろくでなし' },
        { question: 'gedung', answer: '建物' },
        { question: 'clark', answer: 'クラーク' },
        { question: 'luka', answer: '傷' },
        { question: 'kesepakatan', answer: '合意' },
        { question: 'kelihatannya', answer: 'そうみたいです' },
        { question: 'rambut', answer: '髪' },
        { question: 'jawaban', answer: '答え' },
        { question: 'hancur', answer: '破壊された' },
        { question: 'hasil', answer: '結果' },
        { question: 'hatiku', answer: '私の心' },
        { question: 'menari', answer: 'ダンス' },
        { question: 'hewan', answer: '動物' },
        { question: 'berhubungan', answer: '関係する' },
        { question: 'lu', answer: 'あなた' },
        { question: 'bangga', answer: '誇りに思う' },
        { question: 'mengingat', answer: '覚えて' },
        { question: 'uangnya', answer: 'お金' },
        { question: 'memberitahuku', answer: '教えて' },
        { question: 'baju', answer: 'ドレス' },
        { question: 'langkah', answer: 'ステップ' },
        { question: 'tamu', answer: 'ビジター' },
        { question: 'tenanglah', answer: '落ち着け' },
        { question: 'lubang', answer: '穴' },
        { question: 'memberiku', answer: 'ください' },
        { question: 'dibunuh', answer: '殺された' },
        { question: 'pelacur', answer: '売春婦' },
        { question: 'membantuku', answer: '助けて' },
        { question: 'mike', answer: 'マイク' },
        { question: 'menolak', answer: '拒否する' },
        { question: 'maksudnya', answer: 'それはつまり' },
        { question: 'joe', answer: 'ジョー' },
        { question: 'dikatakan', answer: '言われている' },
        { question: 'peluru', answer: '弾丸' },
        { question: 'berharga', answer: '貴重な' },
        { question: 'binatang', answer: '動物' },
        { question: 'menyimpan', answer: '保つ' },
        { question: 'pedang', answer: '剣' },
        { question: 'is', answer: 'は' },
        { question: 'anakmu', answer: 'あなたのお子様' },
        { question: 'charlie', answer: 'チャーリー' },
        { question: 'iblis', answer: '悪魔' },
        { question: 'tarik', answer: '引く' },
        { question: 'penjahat', answer: '犯罪的' },
        { question: 'sobat', answer: '友人' },
        { question: 'kepadaku', answer: '私にとって' },
        { question: 'berbuat', answer: 'する' },
        { question: 'bertindak', answer: '活動' },
        { question: 'tujuh', answer: 'セブン' },
        { question: 'menderita', answer: '苦しむ' },
        { question: 'adil', answer: '公平' },
        { question: 'putus', answer: '分離された' },
        { question: 'negeri', answer: '国' },
        { question: 'bercinta', answer: '愛し合う' },
        { question: 'lemah', answer: '弱い' },
        { question: 'semalam', answer: '一晩中' },
        { question: 'merusak', answer: 'ダメージ' },
        { question: 'suami', answer: '夫' },
        { question: 'pemimpin', answer: 'リーダー' },
        { question: 'haruskah', answer: 'すべき' },
        { question: 'terimakasih', answer: 'ありがとう' },
        { question: 'do', answer: 'する' },
        { question: 'mil', answer: 'マイル' },
        { question: 'masuklah', answer: 'お入りください' },
        { question: 'macam', answer: 'タイプ' },
        { question: 'langit', answer: '空' },
        { question: 'bersembunyi', answer: '隠蔽' },
        { question: 'angin', answer: '風' },
        { question: 'nick', answer: 'ニック' },
        { question: 'terserah', answer: 'あなた次第' },
        { question: 'mama', answer: 'ママ' },
        { question: 'pegang', answer: '所有' },
        { question: 'tv', answer: 'テレビ' },
        { question: 'video', answer: 'ビデオ' },
        { question: 'mengira', answer: '考える' },
        { question: 'untuknya', answer: '彼のために' },
        { question: 'berteriak', answer: '叫ぶ' },
        { question: 'terjebak', answer: '閉じ込められた' },
        { question: 'ganti', answer: '変化' },
        { question: 'sepuluh', answer: '10' },
        { question: 'pulau', answer: '島' },
        { question: 'menahan', answer: '差し控える' },
        { question: 'alex', answer: 'アレックス' },
        { question: 'ketiga', answer: '三番目' },
        { question: 'sederhana', answer: '単純' },
        { question: 'memegang', answer: '所有' },
        { question: 'usah', answer: '必要なし' },
        { question: 'hubungannya', answer: '関係' },
        { question: 'perubahan', answer: '変化' },
        { question: 'hujan', answer: '雨' },
        { question: 'tidakkah', answer: 'そう思いませんか？' },
        { question: 'kucing', answer: '猫' },
        { question: 'memotong', answer: 'カット' },
        { question: 'tanganku', answer: '私の手' },
        { question: 'berjuang', answer: '戦い' },
        { question: 'ben', answer: 'ベン' },
        { question: 'tingkat', answer: 'レベル' },
        { question: 'rumahku', answer: '私の家' },
        { question: 'dendam', answer: '確執' },
        { question: 'max', answer: '最大' },
        { question: 'militer', answer: '軍隊' },
        { question: 'menghadapi', answer: '顔' },
        { question: 'd', answer: 'd' },
        { question: 'pantai', answer: 'ビーチ' },
        { question: 'kode', answer: 'コード' },
        { question: 'saudaraku', answer: '私の兄弟' },
        { question: 'komputer', answer: 'コンピューター' },
        { question: 'kudengar', answer: '私は聞いた' },
        { question: 'sedih', answer: '悲しい' },
        { question: 'your', answer: 'あなたの' },
        { question: 'tas', answer: 'バッグ' },
        { question: 'seekor', answer: '1つ' },
        { question: 'jantung', answer: '心臓' },
        { question: 'dinding', answer: '壁' },
        { question: 'mengambilnya', answer: '持って行って' },
        { question: 'mengurus', answer: '世話をする' },
        { question: 'mobilnya', answer: '彼の車' },
        { question: 'menyedihkan', answer: '悲しい' },
        { question: 'petunjuk', answer: '命令' },
        { question: 'sihir', answer: '魔法' },
        { question: 'bar', answer: 'バー' },
        { question: 'kelompok', answer: 'グループ' },
        { question: 'minggir', answer: '脇に寄る' },
        { question: 'hidupnya', answer: '彼の人生' },
        { question: 'mulut', answer: '口' },
        { question: 'desa', answer: '村' },
        { question: 'menyakiti', answer: '傷つく' },
        { question: 'menyentuh', answer: '触る' },
        { question: 'pertandingan', answer: 'マッチ' },
        { question: 'warga', answer: '住民' },
        { question: 'maukah', answer: 'したいですか' },
        { question: 'jendela', answer: 'ウィンドウ' },
        { question: 'love', answer: '愛' },
        { question: 'lampu', answer: 'ライト' },
        { question: 'we', answer: '私たちは' },
        { question: 'gunung', answer: '山' },
        { question: 'alih', answer: '以上' },
        { question: 'asli', answer: 'オリジナル' },
        { question: 'bibi', answer: '叔母' },
        { question: 'menyebabkan', answer: '原因' },
        { question: 'tom', answer: 'トム' },
        { question: 'pisau', answer: 'ナイフ' },
        { question: 'jane', answer: 'ジェーン' },
        { question: 'garis', answer: 'ライン' },
        { question: 'menjalankan', answer: '操作する' },
        { question: 'menakjubkan', answer: 'すばらしい' },
        { question: 'biru', answer: '青' },
        { question: 'awas', answer: '気をつけて' },
        { question: 'walter', answer: 'ウォルター' },
        { question: 'melupakan', answer: '忘れる' },
        { question: 'kakek', answer: 'おじいちゃん' },
        { question: 'menangani', answer: 'ハンドル' },
        { question: 'kotor', answer: '汚い' },
        { question: 'kata-kata', answer: '言葉' },
        { question: 'konyol', answer: 'バカ' },
        { question: 'cepatlah', answer: '急いで' },
        { question: 'bayangkan', answer: '想像する' },
        { question: 'jumlah', answer: '額' },
        { question: 'sisa', answer: '残り' },
        { question: 'cobalah', answer: '試してみる' },
        { question: 'adikku', answer: '私の姉' },
        { question: 'dr', answer: 'ドクター' },
        { question: 'henry', answer: 'ヘンリー' },
        { question: 'bukannya', answer: 'の代わりに' },
        { question: 'klub', answer: 'クラブ' },
        { question: 'begitulah', answer: 'それがそれだ' },
        { question: 'temui', answer: '会う' },
        { question: 'kotoran', answer: 'ダート' },
        { question: 'darurat', answer: '緊急' },
        { question: 'sarah', answer: 'サラ' },
        { question: 'tampan', answer: 'ハンサム' },
        { question: 'sehat', answer: '健康' },
        { question: 'beli', answer: '買う' },
        { question: 'anaknya', answer: '彼の息子' },
        { question: 'aah', answer: 'ああ' },
        { question: 'utk', answer: 'のために' },
        { question: 'perhatikan', answer: 'メモを取る' },
        { question: 'jepang', answer: '日本' },
        { question: 'lanjutkan', answer: '続く' },
        { question: 'radio', answer: '無線' },
        { question: 'terkejut', answer: '驚いた' },
        { question: 'putriku', answer: '私の娘' },
        { question: 'la', answer: 'ラ' },
        { question: 'pasangan', answer: 'パートナー' },
        { question: 'mary', answer: 'メアリー' },
        { question: 'membersihkan', answer: 'クリーン' },
        { question: 'letakkan', answer: '置く' },
        { question: 'kencan', answer: '日付' },
        { question: 'timur', answer: '東' },
        { question: 'adik', answer: '弟' },
        { question: 'barat', answer: '西' },
        { question: 'allah', answer: 'アッラー' },
        { question: 'terbunuh', answer: '殺された' },
        { question: 'umum', answer: '一般的な' },
        { question: 'listrik', answer: '電気' },
        { question: 'ji', answer: 'ジ' },
        { question: 'for', answer: 'のために' },
        { question: 'wah', answer: 'おお' },
        { question: 'terkadang', answer: '時々' },
        { question: 'mengatur', answer: '整える' },
        { question: 'menakutkan', answer: '怖い' },
        { question: 'memperbaiki', answer: '修理' },
        { question: 'menciptakan', answer: '作成する' },
        { question: 'selamatkan', answer: '保存' },
        { question: 'fokus', answer: '集中' },
        { question: 'memimpin', answer: '鉛' },
        { question: 'tukang', answer: '職人' },
        { question: 'persis', answer: 'その通り' },
        { question: 'teh', answer: 'お茶' },
        { question: 'kehormatan', answer: '名誉' },
        { question: 'nyawa', answer: '人生' },
        { question: 'duduklah', answer: '座って下さい' },
        { question: 'bir', answer: 'ビール' },
        { question: 'memenangkan', answer: '勝つ' },
        { question: 'surga', answer: '天国' },
        { question: 'tes', answer: 'テスト' },
        { question: 'jerman', answer: 'ドイツ語' },
        { question: 'memakan', answer: '食べる' },
        { question: 'permintaan', answer: 'リクエスト' },
        { question: 'gigi', answer: '歯' },
        { question: 'kadang-kadang', answer: '時々' },
        { question: 'lepas', answer: 'オフ' },
        { question: 'bersikap', answer: '振る舞う' },
        { question: 'ma', answer: 'ママ' },
        { question: 'darimana', answer: 'どこから' },
        { question: 'telpon', answer: '電話' },
        { question: 'mantan', answer: '元-' },
        { question: 'idiot', answer: 'ばか' },
        { question: 'setan', answer: '悪魔' },
        { question: 'kebetulan', answer: 'たまたま' },
        { question: 'malah', answer: 'それよりも' },
        { question: 'masyarakat', answer: '公共' },
        { question: 'suruh', answer: '注文' },
        { question: 'gunanya', answer: 'その使用' },
        { question: 'pertempuran', answer: '戦い' },
        { question: 'lelaki', answer: '男' },
        { question: 'kegelapan', answer: '暗闇' },
        { question: 'super', answer: '素晴らしい' },
        { question: 'jenderal', answer: '一般的な' },
        { question: 'buang', answer: '捨てる' },
        { question: 'so', answer: 'それで' },
        { question: 'kepadanya', answer: '彼に' },
        { question: 'rusia', answer: 'ロシア' },
        { question: 'direktur', answer: '監督' },
        { question: 'mengucapkan', answer: '言う' },
        { question: 'diterima', answer: '承認済み' },
        { question: 'delapan', answer: '八' },
        { question: 'anggap', answer: '考慮する' },
        { question: 'letnan', answer: '中尉' },
        { question: 'kena', answer: '打つ' },
        { question: 'babi', answer: '豚' },
        { question: 'istana', answer: '宮殿' },
        { question: 'tanggal', answer: '日付' },
        { question: 'stasiun', answer: '駅' },
        { question: 'selesaikan', answer: '仕上げる' },
        { question: 'lelucon', answer: 'ジョーク' },
        { question: 'vampir', answer: '吸血鬼' },
        { question: 'paul', answer: 'ポール' },
        { question: 'danny', answer: 'ダニー' },
        { question: 'menceritakan', answer: '教えて' },
        { question: 'mengetahuinya', answer: '知っている' },
        { question: 'naga', answer: 'ドラゴン' }
    ];

})();
